name: Mirror branch

on:
  push:
    branches:
      - main

jobs:
  mirror-main-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mirror main branch
        run: "git checkout -b master && git push origin master"
