name: Mirror main branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mirror to master branch
        run: |
          set -e
          if ! git show-ref --quiet master; then
            CHECKOUT_OPTS="-b"
          fi
          git checkout $CHECKOUT_OPTS master
          git rebase main
          git push origin master
