name: Mirror main branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # It will fetch the entire git history (by default this is `fetch-depth: 1`)

      - name: Mirror to master branch
        run: |
          set -e
          if ! git show-ref --quiet master; then
            # Use param to create new branch if the branch doesn't already exist.
            CHECKOUT_OPTS="-b"
          fi
          git checkout $CHECKOUT_OPTS master
          git rebase main
          git push origin master
