name: Mirror main branch

on:
  push:
    branches:
      - main

jobs:
  master-mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mirror main branch to master branch
        run: "git checkout -b master && git push origin master"
        env:
          GITHUB_TOKEN: ${{ github.token }}
